# https://docs.travis-ci.com/user/languages/python/
language: python

# https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches
branches:
  only:
    - master

# https://docs.travis-ci.com/user/encryption-keys/
env:
  global:
    - secure: "aWRNsnhm+OKfU+GYLlE9P07Cqz6CyxfwC/oRJZINHZhJhx9HZwW4WB5UdOxykWJuokkjspaUph1srgZnfDLxYNtEyE0fteTEB2BDMd25lNfx21UndZr45FjjuK6SugY/qtrw86aJy85CtPRxJ3QEO2tEeGO6HSjIopTD8rP64wLIXIXJ2mQtkKnX0NFpEv7RKpV0h7LbrfOoYq9DSXTV/BvOFJSc7jWtuGW+Uc1xGM03g2dKDw7isCmWBTlq4QdUw49kpUX/Ly97aPlk+d2tSr+qD099B/ZbLlQH/KbOQdrMUKkkvyYJmGSzhQzQV1uEg6C9/44vZF+QZTQEnR2zR4lY5PUsjCsGLJ0tXwWRaGmT51W7Smn6efzNrmK6hLSJrZWOjn5OHWOoAxDScbzTZMnidJr8wENhqWIk+WCkuHyvLakE9ojLXRdau098A+wZ3tWH4nJ9Q82S5yhpUzw5T4ePUDzut6/62jymzcrBxHVch9pKLp4/8PSD34Xuxm4jS3X0wvr2A9C7CW5zPHXfCIIVQYpGNG8eO2YixFGW3ESwR7SNLuVJAONqdnYCniJJA+RzyMhVNsv5q8mSqWLPJzl4CljKvtak0+rrXfqXU+ujCHSUf039dC40/Pz86M4qmILQJTyz839Yatpmx9pOmda2/3ilhniDJfSlaSkkS+U="

# https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle
install:
  - pip install git+https://github.com/adblockplus/python-abp
before_script:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "TravisCI"
  - git config --global push.default "matching"

# https://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Build-Step
script:
  - git clone -b gh-pages "https://$GITHUB_TOKEN@github.com/easylist/easylistgermany" output
  - flrender -i easylistgermany=. easylistgermany.template output/easylistgermany.txt
  - cd output && git add --all . && git commit -m "Publishing revision $(git --git-dir ../.git rev-parse --short HEAD)" && git push --force origin gh-pages

