# https://docs.travis-ci.com/user/languages/python/
language: python

# https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches
branches:
  only:
    - master

# https://docs.travis-ci.com/user/encryption-keys/
env:
  global:
    - secure: "0UpYL/8GTqo3UFcAWVrn1FIeGTBMgR1KD01hXTLINTxPlIt3n8wczlfnJpn4s4brUOa5eKp8OON4bHXqBz2i9KD1i0qgwPOGN+tn7IOm0KjrW8FsfDIUx2+Z9HaGCV3HLrZs6NvJVahC2zgONmU5Udrenhk3LTk9caswQ2kHfoNmPuh/WuOUSbM/w0RNSx4rdVrrLzdFG7BVPbeX8uELLMU8n2msiw7oIKjpljaI0Fm3+vuLFCdT0ae4uc/YgPjiJpPIZp+x8Chg0JSA/DYP22SCiVJ29UTDlaRjkY2gJ98qZfhPidv3teUm3meH0R0pBBlSANaQzpqmQQNoiJL81Xa07l+rXN0j+9bjkWlv+XDPTDZHng9AXom/oAWyphDhwjVGWKKxYnw2xgtduRtna4mmHMNTio5ugM1JFxqlx49POy31o+ddV9ZYjWP+JEWX7z+R634+vwAPIpTYsz/+AjLLHlynUigiI+GnBC2BaKp1hS6iH2ZoFWdjVMDTDMkOyKW6fWhF3OZIBdLFNGO8RMa+aZbNTQTnv8mO1KD2mlGCCHguKP7X8gUqrcVKcJmbHHZ9bcXkgYElP2XsYd0+hIr0x9FmM/eSxEHssYiU/Im0OaCYS+VwN2GDnKpneP7nJwZ+l5+jpPpuzfYVzXTAjqlTvUONV8FW7CpAUIcGHGY="

# https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle
install:
  - pip install git+https://github.com/adblockplus/python-abp
before_script:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "TravisCI"
  - git config --global push.default "matching"

# https://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Build-Step
script:
  - git clone -b gh-pages "https://$GITHUB_TOKEN@github.com/easylist/easylistgermany" output
  - flrender -i easylistgermany=. easylistgermany.template output/easylistgermany.txt
  - cd output && git add --all . && git commit -m "Publishing revision $(git --git-dir ../.git rev-parse --short HEAD)" && git push --force origin gh-pages

