# https://docs.travis-ci.com/user/languages/python/
language: python

# https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches
branches:
  only:
    - master

# https://docs.travis-ci.com/user/encryption-keys/
env:
  global:
    - secure: "FSh2Zgv7dJsq/XaEdVr905GKKYJcy/ON3fl4IDnOy3tNQpE9yaJclX4pad8IvY5q/C9+x6xXtTjmQlq6nBvutJjsG96Oj4e5+ofavXT+TZfuFGfE97mznyCZDIFFcUkb+J3JiUYOjVb/UWjjNlA+l7yj5EbePkasBn2uN1rl3O/i6IA9zppzoUJKYiNKsiRwKx+jz8s4z/NHA/SpH7rgh7nBD+fl33DKeYGZFx3AsgQzvivSW98hTEaM6g4bepKEnXeHpG+bNDIjGkXjSY3uggo0p6k0j/KitY9wKTOBBJtd8kdSMVSvv5gqrm6CDDQTHT/FmTWyxMXxjMHuYgn8Xs7io9QYdHsK1jWy3rDh+T/xlNNaQNh3ymfkBcJVi2nveif2XLUm8f3JUkdFsnMfyaLqrogIDo85EKUjDNSZWk0pE0Mo0Yq1k06FkBYZXhO8gKlQiXkucXIn2a6tGPnlQcKVxLng4BzOGZKqlvw8Ik1lL3QI3rp2Vyx7fgubaTI6QIPfxQmOuwBBqdmKh3X606M3BlpO6i5dzM37ZahqrO0lgGsgJY36bjWUpOTDgGeXCFgkyZE7fxwwZrL0HQBnj7Q4fopiG7quamr8Ef2iD+lhcKh20VH//yHV9k145xd/SZ0v35OaIz604xkbKzoAv5V0YHLEj0EHuPixs0fpbsI="

# https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle
install:
  - pip install git+https://github.com/adblockplus/python-abp
before_script:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "TravisCI"
  - git config --global push.default "matching"

# https://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Build-Step
script:
  - git clone -b gh-pages "https://$GITHUB_TOKEN@github.com/easylist/easylistgermany" output
  - flrender -i easylistgermany=. easylistgermany.template output/easylistgermany.txt
  - cd output && git add --all . && git commit -m "Publishing revision $(git --git-dir ../.git rev-parse --short HEAD)" && git push --force origin gh-pages

