# https://docs.travis-ci.com/user/languages/python/
language: python

# https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches
branches:
  only:
    - master

# https://docs.travis-ci.com/user/encryption-keys/
env:
  global:
    - secure: "Lmvx1ydoLZtr13icluCzMsuMYrh9iULt1zafT5+UrxOuD5NErfsCZQ056MudTP3EB0YCBBVpaaT5lSEply4LjmGfBDH6RWy7x/PtqZVKpPx/zm+ns0h0gm1QoBYIHuCs6tXVzgTQHoK5ycz1MfwNFNTYEt6UAN8lveYHfV6alOA0JVK/LJbsXCAoKJhPv/eqP9IPYONnVDBt+hVvyd8vD5tNx1ylo2WKy2gGZP0bGwJukQOLiQQbgndtS3Xvpp5P1SWgkBzX1Bd5J9cB6YdxjDWXYAd4cHo+PjEh42ZaTSDKGmKKL1DviRikWo4LOODxB/x0BN/tZGfQvSW/szfBGA2dsJ92JFAHNFYk0ggq16+Xi2PA2ZRSJd4sDFND/CQNOT12t4gYg0B+4xTaB0fRkx3s86EC/c48lanOPe0rjWckdvghvlKwd4JtmZ89Ke1O9B+UsHSOtM0SakiGLhVGN7ZPOd+CfkqPDgjv47c68h0bbqd6uM3x5whteIzgBON39/WANiXmgvJKFG5YnHel1/PAdnIknSMz6eJVzZM/DY3o5/mbwZ8dyPUP6ovYbzfR2C93gz1cfXnPDfxwTmFwt6Ys5W4IAYnnFrFY5lm1Ij4BQZVnJ3/DlHHlMWGMPDmbxboV9yz+w+fZZERLa2t+a0ldkMfX3rgJLW0OyvT9ayc="

# https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle
install:
  - pip install git+https://github.com/adblockplus/python-abp
before_script:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "TravisCI"
  - git config --global push.default "matching"

# https://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Build-Step
script:
  - git clone -b gh-pages "https://$GITHUB_TOKEN@github.com/easylist/easylistgermany" output
  - flrender -i easylistgermany=. easylistgermany.template output/easylistgermany.txt
  - cd output && git add --all . && git commit -m "Publishing revision $(git --git-dir ../.git rev-parse --short HEAD)" && git push --force origin gh-pages

